Samples: Use Datamanagment API to initiate file transfer
agera-edc/DataSpaceConnector pull request #227
Opened 2022-04-14 13:38 UTC by cpeeyush

## What this PR changes/adds

- Sample04.0-file-transfer doc updated to use DataManagement API for asset transfer.
- Removed existing custom implementation of ConsumerApiController.
- Updated other samples dependency and docs.

## Why it does that

To use DataManagement API.

## Further notes

Follow PR of #221 

## Linked Issue(s)

Closes https://github.com/agera-edc/MinimumViableDataspace/issues/38

## Checklist

- [ ] added appropriate tests?
- [x] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2022-04-16 13:37 UTC, marcgs commented
Suggesting to add the changes in this commit: https://github.com/agera-edc/DataSpaceConnector/commit/8a1ac4bde557a616556d767c5c1652a7176448d5. This enhances the README with instructions how to perform file transfers and shows screenshots of the traces for contract negotiations and file transfers.

Note: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1162 is required for traces in DPF

2022-04-19 09:07 UTC, marcgs requested changes
see inline comment

2022-04-20 09:17 UTC, cpeeyush commented
> Suggesting to add the changes in this commit: [8a1ac4b](https://github.com/agera-edc/DataSpaceConnector/commit/8a1ac4bde557a616556d767c5c1652a7176448d5). This enhances the README with instructions how to perform file transfers and shows screenshots of the traces for contract negotiations and file transfers.
> 
> Note: [eclipse-dataspaceconnector#1162](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1162) is required for traces in DPF

@marcgs  As discussed picked up changes from commit 8a1ac4bde557a616556d767c5c1652a7176448d5 into this PR. Please take a look.

2022-04-20 12:49 UTC, marcgs approved these changes

2022-04-21 12:21 UTC, ouphi approved these changes

2022-04-21 12:53 UTC, merged